kind: "DDT"
use_critic: False
learning_starts: 0
batch_size: 128
gradient_steps: 1
stochastic_policy: False
loss_fn: "ce"
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 2000000000
buffer_weight_by: len 
target_return_type: predefined
warmup_steps: 4000
use_amp: True 
compile: True
bfloat16: True
persist_context: True

replay_buffer_kwargs:
  num_workers: 16
  pin_memory: False
  init_top_p: 1
  seqs_per_sample: 2
  seq_sample_kind: sequential
  full_context_trjs: True

defaults:
  - huggingface: dt_medium_64
  - data_paths: dark_room_10x10_sfixed_grand_train
  - model_kwargs: dark_room
  - lr_sched_kwargs: cosine

huggingface:
  activation_function: gelu
  max_length: 50
  use_fast_attn: True
  n_positions: 1600
eval_context_len: ${agent_params.huggingface.max_length}
