kind: "MDDT"
use_critic: False
learning_starts: 0
batch_size: 128
gradient_steps: 1
stochastic_policy: False
loss_fn: "ce"
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 2000000000
buffer_weight_by: len 
target_return_type: predefined
warmup_steps: 4000
use_amp: True 
compile: True
bfloat16: True

defaults:
  - huggingface: dt_medium_64
  - data_paths: mt45v2_dmc11_pg12_atari41_cs240_mg83
  - model_kwargs: multi_domain
  - lr_sched_kwargs: cosine
  - replay_buffer_kwargs: multi_domain_mtdmccs

huggingface:
  activation_function: gelu
  max_length: 50
  use_fast_attn: True
  n_positions: 1600
eval_context_len: ${agent_params.huggingface.max_length}
