reward_condition: True
tokenize_a: True
tokenize_rtg: False 
action_channels: 256
discrete_actions: 18
state_dim: 204
image_shape: [3,64,64]
relative_pos_embds: False
use_time_embds: False
action_condition: False
shared_a_head: True