# same ones as used in MGDT
# - alien  
- amidar
- assault
- asterix
- atlantis
- bank-heist
- battle-zone
- beam-rider
- boxing
- breakout
- carnival
- centipede
- chopper-command
- crazy-climber
- demon-attack
- double-dunk
- enduro
- fishing-derby
- freeway
- frostbite
- gopher
- gravitar
- hero
- ice-hockey
- jamesbond
- kangaroo
- krull
- kung-fu-master
# - ms-pacman 
- name-this-game
- phoenix
# - pong
- pooyan
- qbert
- riverraid
- road-runner
- robotank
- seaquest
# - space-invaders
# - star-gunner
- time-pilot
- up-n-down
- video-pinball
- wizard-of-wor
- yars-revenge
- zaxxon
