base: ${SSD_DATA_DIR}/composuite/processed
names:
  - IIWA_Box_None_PickPlace
  - IIWA_Box_None_Push
  - IIWA_Box_None_Shelf
  - IIWA_Box_None_Trashcan
  - IIWA_Box_GoalWall_PickPlace
  - IIWA_Box_GoalWall_Push
  - IIWA_Box_GoalWall_Shelf
  - IIWA_Box_GoalWall_Trashcan
  - IIWA_Box_ObjectDoor_PickPlace
  - IIWA_Box_ObjectDoor_Push
  - IIWA_Box_ObjectDoor_Shelf
  - IIWA_Box_ObjectDoor_Trashcan
  - IIWA_Box_ObjectWall_PickPlace
  - IIWA_Box_ObjectWall_Push
  - IIWA_Box_ObjectWall_Shelf
  - IIWA_Box_ObjectWall_Trashcan
  - IIWA_Dumbbell_None_PickPlace
  - IIWA_Dumbbell_None_Push
  - IIWA_Dumbbell_None_Shelf
  - IIWA_Dumbbell_None_Trashcan
  - IIWA_Dumbbell_GoalWall_PickPlace
  - IIWA_Dumbbell_GoalWall_Push
  - IIWA_Dumbbell_GoalWall_Shelf
  - IIWA_Dumbbell_GoalWall_Trashcan
  - IIWA_Dumbbell_ObjectDoor_PickPlace
  - IIWA_Dumbbell_ObjectDoor_Push
  - IIWA_Dumbbell_ObjectDoor_Shelf
  - IIWA_Dumbbell_ObjectDoor_Trashcan
  - IIWA_Dumbbell_ObjectWall_PickPlace
  - IIWA_Dumbbell_ObjectWall_Push
  - IIWA_Dumbbell_ObjectWall_Shelf
  - IIWA_Dumbbell_ObjectWall_Trashcan
  - IIWA_Plate_None_PickPlace
  - IIWA_Plate_None_Push
  - IIWA_Plate_None_Shelf
  - IIWA_Plate_None_Trashcan
  - IIWA_Plate_GoalWall_PickPlace
  - IIWA_Plate_GoalWall_Push
  - IIWA_Plate_GoalWall_Shelf
  - IIWA_Plate_GoalWall_Trashcan
  - IIWA_Plate_ObjectDoor_PickPlace
  - IIWA_Plate_ObjectDoor_Push
  - IIWA_Plate_ObjectDoor_Shelf
  - IIWA_Plate_ObjectDoor_Trashcan
  - IIWA_Plate_ObjectWall_PickPlace
  - IIWA_Plate_ObjectWall_Push
  - IIWA_Plate_ObjectWall_Shelf
  - IIWA_Plate_ObjectWall_Trashcan
  - IIWA_Hollowbox_None_PickPlace
  - IIWA_Hollowbox_None_Push
  - IIWA_Hollowbox_None_Shelf
  - IIWA_Hollowbox_None_Trashcan
  - IIWA_Hollowbox_GoalWall_PickPlace
  - IIWA_Hollowbox_GoalWall_Push
  - IIWA_Hollowbox_GoalWall_Shelf
  - IIWA_Hollowbox_GoalWall_Trashcan
  - IIWA_Hollowbox_ObjectDoor_PickPlace
  - IIWA_Hollowbox_ObjectDoor_Push
  - IIWA_Hollowbox_ObjectDoor_Shelf
  - IIWA_Hollowbox_ObjectDoor_Trashcan
  - IIWA_Hollowbox_ObjectWall_PickPlace
  - IIWA_Hollowbox_ObjectWall_Push
  - IIWA_Hollowbox_ObjectWall_Shelf
  - IIWA_Hollowbox_ObjectWall_Trashcan
  - Jaco_Box_None_PickPlace
  - Jaco_Box_None_Push
  - Jaco_Box_None_Shelf
  - Jaco_Box_None_Trashcan
  - Jaco_Box_GoalWall_PickPlace
  - Jaco_Box_GoalWall_Push
  - Jaco_Box_GoalWall_Shelf
  - Jaco_Box_GoalWall_Trashcan
  - Jaco_Box_ObjectDoor_PickPlace
  - Jaco_Box_ObjectDoor_Push
  - Jaco_Box_ObjectDoor_Shelf
  - Jaco_Box_ObjectDoor_Trashcan
  - Jaco_Box_ObjectWall_PickPlace
  - Jaco_Box_ObjectWall_Push
  - Jaco_Box_ObjectWall_Shelf
  - Jaco_Box_ObjectWall_Trashcan
  - Jaco_Dumbbell_None_PickPlace
  - Jaco_Dumbbell_None_Push
  - Jaco_Dumbbell_None_Shelf
  - Jaco_Dumbbell_None_Trashcan
  - Jaco_Dumbbell_GoalWall_PickPlace
  - Jaco_Dumbbell_GoalWall_Push
  - Jaco_Dumbbell_GoalWall_Shelf
  - Jaco_Dumbbell_GoalWall_Trashcan
  - Jaco_Dumbbell_ObjectDoor_PickPlace
  - Jaco_Dumbbell_ObjectDoor_Push
  - Jaco_Dumbbell_ObjectDoor_Shelf
  - Jaco_Dumbbell_ObjectDoor_Trashcan
  - Jaco_Dumbbell_ObjectWall_PickPlace
  - Jaco_Dumbbell_ObjectWall_Push
  - Jaco_Dumbbell_ObjectWall_Shelf
  - Jaco_Dumbbell_ObjectWall_Trashcan
  - Jaco_Plate_None_PickPlace
  - Jaco_Plate_None_Push
  - Jaco_Plate_None_Shelf
  - Jaco_Plate_None_Trashcan
  - Jaco_Plate_GoalWall_PickPlace
  - Jaco_Plate_GoalWall_Push
  - Jaco_Plate_GoalWall_Shelf
  - Jaco_Plate_GoalWall_Trashcan
  - Jaco_Plate_ObjectDoor_PickPlace
  - Jaco_Plate_ObjectDoor_Push
  - Jaco_Plate_ObjectDoor_Shelf
  - Jaco_Plate_ObjectDoor_Trashcan
  - Jaco_Plate_ObjectWall_PickPlace
  - Jaco_Plate_ObjectWall_Push
  - Jaco_Plate_ObjectWall_Shelf
  - Jaco_Plate_ObjectWall_Trashcan
  - Jaco_Hollowbox_None_PickPlace
  - Jaco_Hollowbox_None_Push
  - Jaco_Hollowbox_None_Shelf
  - Jaco_Hollowbox_None_Trashcan
  - Jaco_Hollowbox_GoalWall_PickPlace
  - Jaco_Hollowbox_GoalWall_Push
  - Jaco_Hollowbox_GoalWall_Shelf
  - Jaco_Hollowbox_GoalWall_Trashcan
  - Jaco_Hollowbox_ObjectDoor_PickPlace
  - Jaco_Hollowbox_ObjectDoor_Push
  - Jaco_Hollowbox_ObjectDoor_Shelf
  - Jaco_Hollowbox_ObjectDoor_Trashcan
  - Jaco_Hollowbox_ObjectWall_PickPlace
  - Jaco_Hollowbox_ObjectWall_Push
  - Jaco_Hollowbox_ObjectWall_Shelf
  - Jaco_Hollowbox_ObjectWall_Trashcan
  - Kinova3_Box_None_PickPlace
  - Kinova3_Box_None_Push
  - Kinova3_Box_None_Shelf
  - Kinova3_Box_None_Trashcan
  - Kinova3_Box_GoalWall_PickPlace
  - Kinova3_Box_GoalWall_Push
  - Kinova3_Box_GoalWall_Shelf
  - Kinova3_Box_GoalWall_Trashcan
  - Kinova3_Box_ObjectDoor_PickPlace
  - Kinova3_Box_ObjectDoor_Push
  - Kinova3_Box_ObjectDoor_Shelf
  - Kinova3_Box_ObjectDoor_Trashcan
  - Kinova3_Box_ObjectWall_PickPlace
  - Kinova3_Box_ObjectWall_Push
  - Kinova3_Box_ObjectWall_Shelf
  - Kinova3_Box_ObjectWall_Trashcan
  - Kinova3_Dumbbell_None_PickPlace
  - Kinova3_Dumbbell_None_Push
  - Kinova3_Dumbbell_None_Shelf
  - Kinova3_Dumbbell_None_Trashcan
  - Kinova3_Dumbbell_GoalWall_PickPlace
  - Kinova3_Dumbbell_GoalWall_Push
  - Kinova3_Dumbbell_GoalWall_Shelf
  - Kinova3_Dumbbell_GoalWall_Trashcan
  - Kinova3_Dumbbell_ObjectDoor_PickPlace
  - Kinova3_Dumbbell_ObjectDoor_Push
  - Kinova3_Dumbbell_ObjectDoor_Shelf
  - Kinova3_Dumbbell_ObjectDoor_Trashcan
  - Kinova3_Dumbbell_ObjectWall_PickPlace
  - Kinova3_Dumbbell_ObjectWall_Push
  - Kinova3_Dumbbell_ObjectWall_Shelf
  - Kinova3_Dumbbell_ObjectWall_Trashcan
  - Kinova3_Plate_None_PickPlace
  - Kinova3_Plate_None_Push
  - Kinova3_Plate_None_Shelf
  - Kinova3_Plate_None_Trashcan
  - Kinova3_Plate_GoalWall_PickPlace
  - Kinova3_Plate_GoalWall_Push
  - Kinova3_Plate_GoalWall_Shelf
  - Kinova3_Plate_GoalWall_Trashcan
  - Kinova3_Plate_ObjectDoor_PickPlace
  - Kinova3_Plate_ObjectDoor_Push
  - Kinova3_Plate_ObjectDoor_Shelf
  - Kinova3_Plate_ObjectDoor_Trashcan
  - Kinova3_Plate_ObjectWall_PickPlace
  - Kinova3_Plate_ObjectWall_Push
  - Kinova3_Plate_ObjectWall_Shelf
  - Kinova3_Plate_ObjectWall_Trashcan
  - Kinova3_Hollowbox_None_PickPlace
  - Kinova3_Hollowbox_None_Push
  - Kinova3_Hollowbox_None_Shelf
  - Kinova3_Hollowbox_None_Trashcan
  - Kinova3_Hollowbox_GoalWall_PickPlace
  - Kinova3_Hollowbox_GoalWall_Push
  - Kinova3_Hollowbox_GoalWall_Shelf
  - Kinova3_Hollowbox_GoalWall_Trashcan
  - Kinova3_Hollowbox_ObjectDoor_PickPlace
  - Kinova3_Hollowbox_ObjectDoor_Push
  - Kinova3_Hollowbox_ObjectDoor_Shelf
  - Kinova3_Hollowbox_ObjectDoor_Trashcan
  - Kinova3_Hollowbox_ObjectWall_PickPlace
  - Kinova3_Hollowbox_ObjectWall_Push
  - Kinova3_Hollowbox_ObjectWall_Shelf
  - Kinova3_Hollowbox_ObjectWall_Trashcan
  - Panda_Box_None_PickPlace
  - Panda_Box_None_Push
  - Panda_Box_None_Shelf
  - Panda_Box_None_Trashcan
  - Panda_Box_GoalWall_PickPlace
  - Panda_Box_GoalWall_Push
  - Panda_Box_GoalWall_Shelf
  - Panda_Box_GoalWall_Trashcan
  - Panda_Box_ObjectDoor_PickPlace
  - Panda_Box_ObjectDoor_Push
  - Panda_Box_ObjectDoor_Shelf
  - Panda_Box_ObjectDoor_Trashcan
  - Panda_Dumbbell_None_PickPlace
  - Panda_Dumbbell_None_Push
  - Panda_Dumbbell_None_Shelf
  - Panda_Dumbbell_None_Trashcan
  - Panda_Dumbbell_GoalWall_PickPlace
  - Panda_Dumbbell_GoalWall_Push
  - Panda_Dumbbell_GoalWall_Shelf
  - Panda_Dumbbell_GoalWall_Trashcan
  - Panda_Dumbbell_ObjectDoor_PickPlace
  - Panda_Dumbbell_ObjectDoor_Push
  - Panda_Dumbbell_ObjectDoor_Shelf
  - Panda_Dumbbell_ObjectDoor_Trashcan
  - Panda_Plate_None_PickPlace
  - Panda_Plate_None_Push
  - Panda_Plate_None_Shelf
  - Panda_Plate_None_Trashcan
  - Panda_Plate_GoalWall_PickPlace
  - Panda_Plate_GoalWall_Push
  - Panda_Plate_GoalWall_Shelf
  - Panda_Plate_GoalWall_Trashcan
  - Panda_Plate_ObjectDoor_PickPlace
  - Panda_Plate_ObjectDoor_Push
  - Panda_Plate_ObjectDoor_Shelf
  - Panda_Plate_ObjectDoor_Trashcan
  - Panda_Hollowbox_None_PickPlace
  - Panda_Hollowbox_None_Push
  - Panda_Hollowbox_None_Shelf
  - Panda_Hollowbox_None_Trashcan
  - Panda_Hollowbox_GoalWall_PickPlace
  - Panda_Hollowbox_GoalWall_Push
  - Panda_Hollowbox_GoalWall_Shelf
  - Panda_Hollowbox_GoalWall_Trashcan
  - Panda_Hollowbox_ObjectDoor_PickPlace
  - Panda_Hollowbox_ObjectDoor_Push
  - Panda_Hollowbox_ObjectDoor_Shelf
  - Panda_Hollowbox_ObjectDoor_Trashcan
