base: ${SSD_DATA_DIR}/mimicgen/core_processed_sparse
names:
  # original mimicgen tasks
  - coffee_d0
  - coffee_d1
  - coffee_d2
  - coffee_preparation_d0
  - coffee_preparation_d1
  - hammer_cleanup_d0
  - hammer_cleanup_d1
  - kitchen_d0
  - kitchen_d1
  - mug_cleanup_d0
  - mug_cleanup_d1
  - nut_assembly_d0
  - pick_place_d0
  - square_d0
  - square_d1
  - square_d2
  - stack_d0
  - stack_d1
  - stack_three_d0
  - stack_three_d1
  - threading_d0
  - threading_d1
  - three_piece_assembly_d0
  - three_piece_assembly_d1
  # self-generate mimicgen data for other robots
  - coffee_D0_robot_IIWA_gripper_Robotiq85Gripper
  - coffee_D0_robot_Sawyer_gripper_RethinkGripper
  - coffee_D0_robot_UR5e_gripper_Robotiq85Gripper
  - coffee_D1_robot_IIWA_gripper_Robotiq85Gripper
  - coffee_D1_robot_Sawyer_gripper_RethinkGripper
  - coffee_D1_robot_UR5e_gripper_Robotiq85Gripper
  - coffee_D2_robot_IIWA_gripper_Robotiq85Gripper
  - coffee_D2_robot_UR5e_gripper_Robotiq85Gripper
  - hammer_cleanup_D0_robot_IIWA_gripper_Robotiq85Gripper
  - hammer_cleanup_D0_robot_Sawyer_gripper_RethinkGripper
  - hammer_cleanup_D0_robot_UR5e_gripper_Robotiq85Gripper
  - hammer_cleanup_D1_robot_IIWA_gripper_Robotiq85Gripper
  - hammer_cleanup_D1_robot_Sawyer_gripper_RethinkGripper
  - hammer_cleanup_D1_robot_UR5e_gripper_Robotiq85Gripper
  - kitchen_D0_robot_IIWA_gripper_Robotiq85Gripper
  - kitchen_D0_robot_UR5e_gripper_Robotiq85Gripper
  - kitchen_D1_robot_UR5e_gripper_Robotiq85Gripper
  - mug_cleanup_D0_robot_IIWA_gripper_Robotiq85Gripper
  - mug_cleanup_D1_robot_IIWA_gripper_Robotiq85Gripper
  - mug_cleanup_D1_robot_UR5e_gripper_Robotiq85Gripper
  # - mug_cleanup_O2_robot_UR5e_gripper_Robotiq85Gripper
  - nut_assembly_D0_robot_IIWA_gripper_Robotiq85Gripper
  - nut_assembly_D0_robot_Sawyer_gripper_RethinkGripper
  - nut_assembly_D0_robot_UR5e_gripper_Robotiq85Gripper
  - pick_place_D0_robot_IIWA_gripper_Robotiq85Gripper
  - pick_place_D0_robot_Sawyer_gripper_RethinkGripper
  - pick_place_D0_robot_UR5e_gripper_Robotiq85Gripper
  - square_D0_robot_IIWA_gripper_Robotiq85Gripper
  - square_D0_robot_Sawyer_gripper_RethinkGripper
  - square_D0_robot_UR5e_gripper_Robotiq85Gripper
  - square_D1_robot_IIWA_gripper_Robotiq85Gripper
  - square_D1_robot_Sawyer_gripper_RethinkGripper
  - square_D1_robot_UR5e_gripper_Robotiq85Gripper
  - stack_D0_robot_IIWA_gripper_Robotiq85Gripper
  - stack_D0_robot_Sawyer_gripper_RethinkGripper
  - stack_D0_robot_UR5e_gripper_Robotiq85Gripper
  - stack_D1_robot_IIWA_gripper_Robotiq85Gripper
  - stack_D1_robot_Sawyer_gripper_RethinkGripper
  - stack_D1_robot_UR5e_gripper_Robotiq85Gripper
  - stack_three_D0_robot_IIWA_gripper_Robotiq85Gripper
  - stack_three_D0_robot_Sawyer_gripper_RethinkGripper
  - stack_three_D0_robot_UR5e_gripper_Robotiq85Gripper
  - stack_three_D1_robot_IIWA_gripper_Robotiq85Gripper
  - stack_three_D1_robot_Sawyer_gripper_RethinkGripper
  - stack_three_D1_robot_UR5e_gripper_Robotiq85Gripper
  - threading_D0_robot_IIWA_gripper_Robotiq85Gripper
  - threading_D0_robot_Sawyer_gripper_RethinkGripper
  - threading_D0_robot_UR5e_gripper_Robotiq85Gripper
  - threading_D1_robot_IIWA_gripper_Robotiq85Gripper
  - threading_D1_robot_Sawyer_gripper_RethinkGripper
  - threading_D1_robot_UR5e_gripper_Robotiq85Gripper
  - three_piece_assembly_D0_robot_IIWA_gripper_Robotiq85Gripper
  - three_piece_assembly_D0_robot_Sawyer_gripper_RethinkGripper
  - three_piece_assembly_D0_robot_UR5e_gripper_Robotiq85Gripper
  - three_piece_assembly_D1_robot_IIWA_gripper_Robotiq85Gripper
  - three_piece_assembly_D1_robot_Sawyer_gripper_RethinkGripper
  - three_piece_assembly_D1_robot_UR5e_gripper_Robotiq85Gripper
  - three_piece_assembly_D2_robot_IIWA_gripper_Robotiq85Gripper
  - three_piece_assembly_D2_robot_Sawyer_gripper_RethinkGripper
  - three_piece_assembly_D2_robot_UR5e_gripper_Robotiq85Gripper
