mt40_v2: 
  base: ${SSD_DATA_DIR}/metaworld
  names: 
    - reach-v2
    - push-v2
    - pick-place-v2
    - door-open-v2
    - drawer-open-v2
    - drawer-close-v2
    - button-press-topdown-v2
    - peg-insert-side-v2
    - window-open-v2
    - window-close-v2
    - door-close-v2
    - reach-wall-v2
    - pick-place-wall-v2
    - push-wall-v2
    - button-press-v2
    - button-press-topdown-wall-v2
    - button-press-wall-v2
    - peg-unplug-side-v2
    - disassemble-v2
    - hammer-v2
    - plate-slide-v2
    - plate-slide-side-v2
    - plate-slide-back-v2
    - plate-slide-back-side-v2
    - handle-press-v2
    - handle-pull-v2
    - handle-press-side-v2
    - handle-pull-side-v2
    - stick-push-v2
    - stick-pull-v2
    - basketball-v2
    - soccer-v2
    - faucet-open-v2
    - faucet-close-v2
    - coffee-push-v2
    - coffee-pull-v2
    - coffee-button-v2
    - sweep-v2
    - sweep-into-v2
    - pick-out-of-hole-v2
    - assembly-v2
    - shelf-place-v2
    - push-back-v2
    - lever-pull-v2
    - dial-turn-v2
dmcontrol: 
  base: ${SSD_DATA_DIR}/dmc
  names: 
    - ball_in_cup-catch
    - cartpole-swingup
    - cheetah-run
    - finger-spin
    - finger-turn_easy
    - fish-upright
    - hopper-stand
    - point_mass-easy
    - reacher-easy
    - walker-run
    - walker-stand
procgen: 
  base: ${SSD_DATA_DIR}/procgen/processed_25M_custom
  names: 
    - "bigfish"
    - "bossfight"
    - "caveflyer"
    - "chaser"
    - "coinrun"
    - "dodgeball" 
    - "fruitbot"
    - "heist"
    - "leaper"
    - "maze"
    - "miner"
    - "starpilot"
atari: 
  base: ${SSD_DATA_DIR}/atari_1M_64rgb
  names: 
    - amidar
    - assault
    - asterix
    - atlantis
    - bank-heist
    - battle-zone
    - beam-rider
    - boxing
    - breakout
    - carnival
    - centipede
    - chopper-command
    - crazy-climber
    - demon-attack
    - double-dunk
    - enduro
    - fishing-derby
    - freeway
    - frostbite
    - gopher
    - gravitar
    - hero
    - ice-hockey
    - jamesbond
    - kangaroo
    - krull
    - kung-fu-master
    - name-this-game
    - phoenix
    - pooyan
    - qbert
    - riverraid
    - road-runner
    - robotank
    - seaquest
    - time-pilot
    - up-n-down
    - video-pinball
    - wizard-of-wor
    - yars-revenge
    - zaxxon
composuite: 
  base: ${SSD_DATA_DIR}/composuite/processed
  names:
    - IIWA_Box_None_PickPlace
    - IIWA_Box_None_Push
    - IIWA_Box_None_Shelf
    - IIWA_Box_None_Trashcan
    - IIWA_Box_GoalWall_PickPlace
    - IIWA_Box_GoalWall_Push
    - IIWA_Box_GoalWall_Shelf
    - IIWA_Box_GoalWall_Trashcan
    - IIWA_Box_ObjectDoor_PickPlace
    - IIWA_Box_ObjectDoor_Push
    - IIWA_Box_ObjectDoor_Shelf
    - IIWA_Box_ObjectDoor_Trashcan
    - IIWA_Box_ObjectWall_PickPlace
    - IIWA_Box_ObjectWall_Push
    - IIWA_Box_ObjectWall_Shelf
    - IIWA_Box_ObjectWall_Trashcan
    - IIWA_Dumbbell_None_PickPlace
    - IIWA_Dumbbell_None_Push
    - IIWA_Dumbbell_None_Shelf
    - IIWA_Dumbbell_None_Trashcan
    - IIWA_Dumbbell_GoalWall_PickPlace
    - IIWA_Dumbbell_GoalWall_Push
    - IIWA_Dumbbell_GoalWall_Shelf
    - IIWA_Dumbbell_GoalWall_Trashcan
    - IIWA_Dumbbell_ObjectDoor_PickPlace
    - IIWA_Dumbbell_ObjectDoor_Push
    - IIWA_Dumbbell_ObjectDoor_Shelf
    - IIWA_Dumbbell_ObjectDoor_Trashcan
    - IIWA_Dumbbell_ObjectWall_PickPlace
    - IIWA_Dumbbell_ObjectWall_Push
    - IIWA_Dumbbell_ObjectWall_Shelf
    - IIWA_Dumbbell_ObjectWall_Trashcan
    - IIWA_Plate_None_PickPlace
    - IIWA_Plate_None_Push
    - IIWA_Plate_None_Shelf
    - IIWA_Plate_None_Trashcan
    - IIWA_Plate_GoalWall_PickPlace
    - IIWA_Plate_GoalWall_Push
    - IIWA_Plate_GoalWall_Shelf
    - IIWA_Plate_GoalWall_Trashcan
    - IIWA_Plate_ObjectDoor_PickPlace
    - IIWA_Plate_ObjectDoor_Push
    - IIWA_Plate_ObjectDoor_Shelf
    - IIWA_Plate_ObjectDoor_Trashcan
    - IIWA_Plate_ObjectWall_PickPlace
    - IIWA_Plate_ObjectWall_Push
    - IIWA_Plate_ObjectWall_Shelf
    - IIWA_Plate_ObjectWall_Trashcan
    - IIWA_Hollowbox_None_PickPlace
    - IIWA_Hollowbox_None_Push
    - IIWA_Hollowbox_None_Shelf
    - IIWA_Hollowbox_None_Trashcan
    - IIWA_Hollowbox_GoalWall_PickPlace
    - IIWA_Hollowbox_GoalWall_Push
    - IIWA_Hollowbox_GoalWall_Shelf
    - IIWA_Hollowbox_GoalWall_Trashcan
    - IIWA_Hollowbox_ObjectDoor_PickPlace
    - IIWA_Hollowbox_ObjectDoor_Push
    - IIWA_Hollowbox_ObjectDoor_Shelf
    - IIWA_Hollowbox_ObjectDoor_Trashcan
    - IIWA_Hollowbox_ObjectWall_PickPlace
    - IIWA_Hollowbox_ObjectWall_Push
    - IIWA_Hollowbox_ObjectWall_Shelf
    - IIWA_Hollowbox_ObjectWall_Trashcan
    - Jaco_Box_None_PickPlace
    - Jaco_Box_None_Push
    - Jaco_Box_None_Shelf
    - Jaco_Box_None_Trashcan
    - Jaco_Box_GoalWall_PickPlace
    - Jaco_Box_GoalWall_Push
    - Jaco_Box_GoalWall_Shelf
    - Jaco_Box_GoalWall_Trashcan
    - Jaco_Box_ObjectDoor_PickPlace
    - Jaco_Box_ObjectDoor_Push
    - Jaco_Box_ObjectDoor_Shelf
    - Jaco_Box_ObjectDoor_Trashcan
    - Jaco_Box_ObjectWall_PickPlace
    - Jaco_Box_ObjectWall_Push
    - Jaco_Box_ObjectWall_Shelf
    - Jaco_Box_ObjectWall_Trashcan
    - Jaco_Dumbbell_None_PickPlace
    - Jaco_Dumbbell_None_Push
    - Jaco_Dumbbell_None_Shelf
    - Jaco_Dumbbell_None_Trashcan
    - Jaco_Dumbbell_GoalWall_PickPlace
    - Jaco_Dumbbell_GoalWall_Push
    - Jaco_Dumbbell_GoalWall_Shelf
    - Jaco_Dumbbell_GoalWall_Trashcan
    - Jaco_Dumbbell_ObjectDoor_PickPlace
    - Jaco_Dumbbell_ObjectDoor_Push
    - Jaco_Dumbbell_ObjectDoor_Shelf
    - Jaco_Dumbbell_ObjectDoor_Trashcan
    - Jaco_Dumbbell_ObjectWall_PickPlace
    - Jaco_Dumbbell_ObjectWall_Push
    - Jaco_Dumbbell_ObjectWall_Shelf
    - Jaco_Dumbbell_ObjectWall_Trashcan
    - Jaco_Plate_None_PickPlace
    - Jaco_Plate_None_Push
    - Jaco_Plate_None_Shelf
    - Jaco_Plate_None_Trashcan
    - Jaco_Plate_GoalWall_PickPlace
    - Jaco_Plate_GoalWall_Push
    - Jaco_Plate_GoalWall_Shelf
    - Jaco_Plate_GoalWall_Trashcan
    - Jaco_Plate_ObjectDoor_PickPlace
    - Jaco_Plate_ObjectDoor_Push
    - Jaco_Plate_ObjectDoor_Shelf
    - Jaco_Plate_ObjectDoor_Trashcan
    - Jaco_Plate_ObjectWall_PickPlace
    - Jaco_Plate_ObjectWall_Push
    - Jaco_Plate_ObjectWall_Shelf
    - Jaco_Plate_ObjectWall_Trashcan
    - Jaco_Hollowbox_None_PickPlace
    - Jaco_Hollowbox_None_Push
    - Jaco_Hollowbox_None_Shelf
    - Jaco_Hollowbox_None_Trashcan
    - Jaco_Hollowbox_GoalWall_PickPlace
    - Jaco_Hollowbox_GoalWall_Push
    - Jaco_Hollowbox_GoalWall_Shelf
    - Jaco_Hollowbox_GoalWall_Trashcan
    - Jaco_Hollowbox_ObjectDoor_PickPlace
    - Jaco_Hollowbox_ObjectDoor_Push
    - Jaco_Hollowbox_ObjectDoor_Shelf
    - Jaco_Hollowbox_ObjectDoor_Trashcan
    - Jaco_Hollowbox_ObjectWall_PickPlace
    - Jaco_Hollowbox_ObjectWall_Push
    - Jaco_Hollowbox_ObjectWall_Shelf
    - Jaco_Hollowbox_ObjectWall_Trashcan
    - Kinova3_Box_None_PickPlace
    - Kinova3_Box_None_Push
    - Kinova3_Box_None_Shelf
    - Kinova3_Box_None_Trashcan
    - Kinova3_Box_GoalWall_PickPlace
    - Kinova3_Box_GoalWall_Push
    - Kinova3_Box_GoalWall_Shelf
    - Kinova3_Box_GoalWall_Trashcan
    - Kinova3_Box_ObjectDoor_PickPlace
    - Kinova3_Box_ObjectDoor_Push
    - Kinova3_Box_ObjectDoor_Shelf
    - Kinova3_Box_ObjectDoor_Trashcan
    - Kinova3_Box_ObjectWall_PickPlace
    - Kinova3_Box_ObjectWall_Push
    - Kinova3_Box_ObjectWall_Shelf
    - Kinova3_Box_ObjectWall_Trashcan
    - Kinova3_Dumbbell_None_PickPlace
    - Kinova3_Dumbbell_None_Push
    - Kinova3_Dumbbell_None_Shelf
    - Kinova3_Dumbbell_None_Trashcan
    - Kinova3_Dumbbell_GoalWall_PickPlace
    - Kinova3_Dumbbell_GoalWall_Push
    - Kinova3_Dumbbell_GoalWall_Shelf
    - Kinova3_Dumbbell_GoalWall_Trashcan
    - Kinova3_Dumbbell_ObjectDoor_PickPlace
    - Kinova3_Dumbbell_ObjectDoor_Push
    - Kinova3_Dumbbell_ObjectDoor_Shelf
    - Kinova3_Dumbbell_ObjectDoor_Trashcan
    - Kinova3_Dumbbell_ObjectWall_PickPlace
    - Kinova3_Dumbbell_ObjectWall_Push
    - Kinova3_Dumbbell_ObjectWall_Shelf
    - Kinova3_Dumbbell_ObjectWall_Trashcan
    - Kinova3_Plate_None_PickPlace
    - Kinova3_Plate_None_Push
    - Kinova3_Plate_None_Shelf
    - Kinova3_Plate_None_Trashcan
    - Kinova3_Plate_GoalWall_PickPlace
    - Kinova3_Plate_GoalWall_Push
    - Kinova3_Plate_GoalWall_Shelf
    - Kinova3_Plate_GoalWall_Trashcan
    - Kinova3_Plate_ObjectDoor_PickPlace
    - Kinova3_Plate_ObjectDoor_Push
    - Kinova3_Plate_ObjectDoor_Shelf
    - Kinova3_Plate_ObjectDoor_Trashcan
    - Kinova3_Plate_ObjectWall_PickPlace
    - Kinova3_Plate_ObjectWall_Push
    - Kinova3_Plate_ObjectWall_Shelf
    - Kinova3_Plate_ObjectWall_Trashcan
    - Kinova3_Hollowbox_None_PickPlace
    - Kinova3_Hollowbox_None_Push
    - Kinova3_Hollowbox_None_Shelf
    - Kinova3_Hollowbox_None_Trashcan
    - Kinova3_Hollowbox_GoalWall_PickPlace
    - Kinova3_Hollowbox_GoalWall_Push
    - Kinova3_Hollowbox_GoalWall_Shelf
    - Kinova3_Hollowbox_GoalWall_Trashcan
    - Kinova3_Hollowbox_ObjectDoor_PickPlace
    - Kinova3_Hollowbox_ObjectDoor_Push
    - Kinova3_Hollowbox_ObjectDoor_Shelf
    - Kinova3_Hollowbox_ObjectDoor_Trashcan
    - Kinova3_Hollowbox_ObjectWall_PickPlace
    - Kinova3_Hollowbox_ObjectWall_Push
    - Kinova3_Hollowbox_ObjectWall_Shelf
    - Kinova3_Hollowbox_ObjectWall_Trashcan
    - Panda_Box_None_PickPlace
    - Panda_Box_None_Push
    - Panda_Box_None_Shelf
    - Panda_Box_None_Trashcan
    - Panda_Box_GoalWall_PickPlace
    - Panda_Box_GoalWall_Push
    - Panda_Box_GoalWall_Shelf
    - Panda_Box_GoalWall_Trashcan
    - Panda_Box_ObjectDoor_PickPlace
    - Panda_Box_ObjectDoor_Push
    - Panda_Box_ObjectDoor_Shelf
    - Panda_Box_ObjectDoor_Trashcan
    - Panda_Dumbbell_None_PickPlace
    - Panda_Dumbbell_None_Push
    - Panda_Dumbbell_None_Shelf
    - Panda_Dumbbell_None_Trashcan
    - Panda_Dumbbell_GoalWall_PickPlace
    - Panda_Dumbbell_GoalWall_Push
    - Panda_Dumbbell_GoalWall_Shelf
    - Panda_Dumbbell_GoalWall_Trashcan
    - Panda_Dumbbell_ObjectDoor_PickPlace
    - Panda_Dumbbell_ObjectDoor_Push
    - Panda_Dumbbell_ObjectDoor_Shelf
    - Panda_Dumbbell_ObjectDoor_Trashcan
    - Panda_Plate_None_PickPlace
    - Panda_Plate_None_Push
    - Panda_Plate_None_Shelf
    - Panda_Plate_None_Trashcan
    - Panda_Plate_GoalWall_PickPlace
    - Panda_Plate_GoalWall_Push
    - Panda_Plate_GoalWall_Shelf
    - Panda_Plate_GoalWall_Trashcan
    - Panda_Plate_ObjectDoor_PickPlace
    - Panda_Plate_ObjectDoor_Push
    - Panda_Plate_ObjectDoor_Shelf
    - Panda_Plate_ObjectDoor_Trashcan
    - Panda_Hollowbox_None_PickPlace
    - Panda_Hollowbox_None_Push
    - Panda_Hollowbox_None_Shelf
    - Panda_Hollowbox_None_Trashcan
    - Panda_Hollowbox_GoalWall_PickPlace
    - Panda_Hollowbox_GoalWall_Push
    - Panda_Hollowbox_GoalWall_Shelf
    - Panda_Hollowbox_GoalWall_Trashcan
    - Panda_Hollowbox_ObjectDoor_PickPlace
    - Panda_Hollowbox_ObjectDoor_Push
    - Panda_Hollowbox_ObjectDoor_Shelf
    - Panda_Hollowbox_ObjectDoor_Trashcan
mimicgen:
  base: ${SSD_DATA_DIR}/mimicgen/core_processed_sparse
  names:
    # original mimicgen tasks
    - coffee_d0
    - coffee_d1
    - coffee_d2
    - coffee_preparation_d0
    - coffee_preparation_d1
    - hammer_cleanup_d0
    - hammer_cleanup_d1
    - kitchen_d0
    - kitchen_d1
    - mug_cleanup_d0
    - mug_cleanup_d1
    - nut_assembly_d0
    - pick_place_d0
    - square_d0
    - square_d1
    - square_d2
    - stack_d0
    - stack_d1
    - stack_three_d0
    - stack_three_d1
    - threading_d0
    - threading_d1
    - three_piece_assembly_d0
    - three_piece_assembly_d1
    # self-generate mimicgen data for other robots
    - coffee_D0_robot_IIWA_gripper_Robotiq85Gripper
    - coffee_D0_robot_Sawyer_gripper_RethinkGripper
    - coffee_D0_robot_UR5e_gripper_Robotiq85Gripper
    - coffee_D1_robot_IIWA_gripper_Robotiq85Gripper
    - coffee_D1_robot_Sawyer_gripper_RethinkGripper
    - coffee_D1_robot_UR5e_gripper_Robotiq85Gripper
    - coffee_D2_robot_IIWA_gripper_Robotiq85Gripper
    - coffee_D2_robot_UR5e_gripper_Robotiq85Gripper
    - hammer_cleanup_D0_robot_IIWA_gripper_Robotiq85Gripper
    - hammer_cleanup_D0_robot_Sawyer_gripper_RethinkGripper
    - hammer_cleanup_D0_robot_UR5e_gripper_Robotiq85Gripper
    - hammer_cleanup_D1_robot_IIWA_gripper_Robotiq85Gripper
    - hammer_cleanup_D1_robot_Sawyer_gripper_RethinkGripper
    - hammer_cleanup_D1_robot_UR5e_gripper_Robotiq85Gripper
    - kitchen_D0_robot_IIWA_gripper_Robotiq85Gripper
    - kitchen_D0_robot_UR5e_gripper_Robotiq85Gripper
    - kitchen_D1_robot_UR5e_gripper_Robotiq85Gripper
    - mug_cleanup_D0_robot_IIWA_gripper_Robotiq85Gripper
    - mug_cleanup_D1_robot_IIWA_gripper_Robotiq85Gripper
    - mug_cleanup_D1_robot_UR5e_gripper_Robotiq85Gripper
    # - mug_cleanup_O2_robot_UR5e_gripper_Robotiq85Gripper
    - nut_assembly_D0_robot_IIWA_gripper_Robotiq85Gripper
    - nut_assembly_D0_robot_Sawyer_gripper_RethinkGripper
    - nut_assembly_D0_robot_UR5e_gripper_Robotiq85Gripper
    - pick_place_D0_robot_IIWA_gripper_Robotiq85Gripper
    - pick_place_D0_robot_Sawyer_gripper_RethinkGripper
    - pick_place_D0_robot_UR5e_gripper_Robotiq85Gripper
    - square_D0_robot_IIWA_gripper_Robotiq85Gripper
    - square_D0_robot_Sawyer_gripper_RethinkGripper
    - square_D0_robot_UR5e_gripper_Robotiq85Gripper
    - square_D1_robot_IIWA_gripper_Robotiq85Gripper
    - square_D1_robot_Sawyer_gripper_RethinkGripper
    - square_D1_robot_UR5e_gripper_Robotiq85Gripper
    - stack_D0_robot_IIWA_gripper_Robotiq85Gripper
    - stack_D0_robot_Sawyer_gripper_RethinkGripper
    - stack_D0_robot_UR5e_gripper_Robotiq85Gripper
    - stack_D1_robot_IIWA_gripper_Robotiq85Gripper
    - stack_D1_robot_Sawyer_gripper_RethinkGripper
    - stack_D1_robot_UR5e_gripper_Robotiq85Gripper
    - stack_three_D0_robot_IIWA_gripper_Robotiq85Gripper
    - stack_three_D0_robot_Sawyer_gripper_RethinkGripper
    - stack_three_D0_robot_UR5e_gripper_Robotiq85Gripper
    - stack_three_D1_robot_IIWA_gripper_Robotiq85Gripper
    - stack_three_D1_robot_Sawyer_gripper_RethinkGripper
    - stack_three_D1_robot_UR5e_gripper_Robotiq85Gripper
    - threading_D0_robot_IIWA_gripper_Robotiq85Gripper
    - threading_D0_robot_Sawyer_gripper_RethinkGripper
    - threading_D0_robot_UR5e_gripper_Robotiq85Gripper
    - threading_D1_robot_IIWA_gripper_Robotiq85Gripper
    - threading_D1_robot_Sawyer_gripper_RethinkGripper
    - threading_D1_robot_UR5e_gripper_Robotiq85Gripper
    - three_piece_assembly_D0_robot_IIWA_gripper_Robotiq85Gripper
    - three_piece_assembly_D0_robot_Sawyer_gripper_RethinkGripper
    - three_piece_assembly_D0_robot_UR5e_gripper_Robotiq85Gripper
    - three_piece_assembly_D1_robot_IIWA_gripper_Robotiq85Gripper
    - three_piece_assembly_D1_robot_Sawyer_gripper_RethinkGripper
    - three_piece_assembly_D1_robot_UR5e_gripper_Robotiq85Gripper
    - three_piece_assembly_D2_robot_IIWA_gripper_Robotiq85Gripper
    - three_piece_assembly_D2_robot_Sawyer_gripper_RethinkGripper
    - three_piece_assembly_D2_robot_UR5e_gripper_Robotiq85Gripper